spring:
    datasource:
        url: jdbc:postgresql://localhost/radio_manager
        username: postgres
        password: 
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: false
        properties:
            hibernate:
                format_sql: false
    application:
        name: demo
